version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    extra_hosts:
      - "jenkins-dockerhost:${JENKINS_DOCKERHOST_IP}"

  jenkins:
    build:
      context: ./jenkins-data
    command: --prefix=/jenkins --logfile=/var/jenkins_home/jenkins.log
    ports:
      - "9115:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    volumes_from:
      - jenkins-data

  jenkins-data:
    build:
      context: ./jenkins-data
      args:
        JENKINS_DOCKERHOST_IP: $JENKINS_DOCKERHOST_IP
    command: /bin/true
    volumes:
      - /var/jenkins_home
~
~
